name: Console Clean Validation

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  validate-console:
    name: Console Clean Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate console output
      run: npm run validate:console
      
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          try {
            execSync('npm run validate:console', { stdio: 'pipe' });
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Console Clean Validation Passed**\n\nNo unwanted console logs, debug statements, or hardcoded credentials found. Code is clean and production-ready.'
            });
          } catch (error) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Console Clean Validation Failed**\n\nFound unwanted console statements, debug code, or hardcoded credentials. Please clean up:\n\n- Remove console.log statements\n- Remove debugger statements\n- Remove hardcoded credentials\n- Use environment variables for sensitive data'
            });
          } 