name: Branch Name Validation

on:
  pull_request:
    branches: [ main, master ]

jobs:
  validate-branch-name:
    name: Branch Naming Convention
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate branch name
      run: |
        BRANCH_NAME="${{ github.head_ref }}"
        
        # Branch naming patterns
        FEATURE_PATTERN="^feature/"
        BUGFIX_PATTERN="^bugfix/"
        HOTFIX_PATTERN="^hotfix/"
        
        echo "🔍 Validating branch name: $BRANCH_NAME"
        
        if [[ $BRANCH_NAME =~ $FEATURE_PATTERN ]] || \
           [[ $BRANCH_NAME =~ $BUGFIX_PATTERN ]] || \
           [[ $BRANCH_NAME =~ $HOTFIX_PATTERN ]]; then
          echo "✅ Branch name follows convention"
          exit 0
        else
          echo "❌ Branch name does not follow convention"
          echo "Expected patterns:"
          echo "  - feature/description (e.g., feature/login-automation)"
          echo "  - bugfix/description (e.g., bugfix/login-error-handling)"
          echo "  - hotfix/description (e.g., hotfix/critical-login-fix)"
          exit 1
        fi
      
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const branchName = context.payload.pull_request.head.ref;
          const featurePattern = /^feature\//;
          const bugfixPattern = /^bugfix\//;
          const hotfixPattern = /^hotfix\//;
          
          if (featurePattern.test(branchName) || bugfixPattern.test(branchName) || hotfixPattern.test(branchName)) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Branch Name Validation Passed**\n\nBranch name follows the established convention:\n\n- `feature/` - New features\n- `bugfix/` - Bug fixes\n- `hotfix/` - Critical fixes'
            });
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Branch Name Validation Failed**\n\nBranch name must follow one of these patterns:\n\n- `feature/description` (e.g., `feature/login-automation`)\n- `bugfix/description` (e.g., `bugfix/login-error-handling`)\n- `hotfix/description` (e.g., `hotfix/critical-login-fix`)\n\nPlease rename your branch to follow the convention.'
            });
          } 